=== 2pages/FieldWorksMacOS/ww/TestData/XMLFieldWorksParse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Randy Regnier (SIL International) -->
<!--W3C Schema generated by XML Spy v3.5 NT (http://www.xmlspy.com)-->
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="AnalyzingAgentResults">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="AnalyzingAgent">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="StateInformation">
								<xsd:complexType/>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="name" type="xsd:string" use="required"/>
						<xsd:attribute name="human" type="xsd:boolean" use="required"/>
						<xsd:attribute name="version" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="WordSet">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="WordForm" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="WfiAnalysis" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="Morphs">
														<xsd:complexType>
															<xsd:sequence>
																<xsd:element name="Morph" maxOccurs="unbounded">
																	<xsd:complexType>
																		<xsd:sequence>
																			<xsd:element name="MoForm">
																				<xsd:complexType>
																					<xsd:attribute name="DbRef" use="required">
																						<xsd:simpleType>
																							<xsd:restriction base="xsd:NMTOKEN">
																								<xsd:enumeration value="1234"/>
																								<xsd:enumeration value="1236"/>
																								<xsd:enumeration value="1500"/>
																								<xsd:enumeration value="6000"/>
																							</xsd:restriction>
																						</xsd:simpleType>
																					</xsd:attribute>
																					<xsd:attribute name="Label" use="required">
																						<xsd:simpleType>
																							<xsd:restriction base="xsd:NMTOKEN">
																								<xsd:enumeration value="-s"/>
																								<xsd:enumeration value="bear"/>
																								<xsd:enumeration value="eat"/>
																							</xsd:restriction>
																						</xsd:simpleType>
																					</xsd:attribute>
																				</xsd:complexType>
																			</xsd:element>
																			<xsd:element name="MSI">
																				<xsd:complexType>
																					<xsd:attribute name="DbRef" use="required">
																						<xsd:simpleType>
																							<xsd:restriction base="xsd:NMTOKEN">
																								<xsd:enumeration value="1235"/>
																								<xsd:enumeration value="1237"/>
																								<xsd:enumeration value="1238"/>
																								<xsd:enumeration value="1239"/>
																								<xsd:enumeration value="1501"/>
																							</xsd:restriction>
																						</xsd:simpleType>
																					</xsd:attribute>
																					<xsd:attribute name="Label" use="required">
																						<xsd:simpleType>
																							<xsd:restriction base="xsd:NMTOKEN">
																								<xsd:enumeration value="3.sg.agr"/>
																								<xsd:enumeration value="PL"/>
																								<xsd:enumeration value="noun"/>
																								<xsd:enumeration value="v.t."/>
																								<xsd:enumeration value="verb"/>
																							</xsd:restriction>
																						</xsd:simpleType>
																					</xsd:attribute>
																				</xsd:complexType>
																			</xsd:element>
																		</xsd:sequence>
																	</xsd:complexType>
																</xsd:element>
															</xsd:sequence>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="DbRef" type="xsd:short"/>
									<xsd:attribute name="Form" type="xsd:string"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== 2pages/FieldWorksMacOS/ww/TestData/SampleM3ParserOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<AnalyzingAgentResults xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\ww\code\SampleData\XMLFieldWorksParse.xsd">
	<AnalyzingAgent name="M3" human="false" version="Normal">
		<StateInformation/>
	</AnalyzingAgent>
	<WordSet>
		<WordForm DbRef="1637" Form="bears">
			<WfiAnalysis>
				<Morphs>
					<Morph>
						<MoForm DbRef="1234" Label="bear"/>
						<MSI DbRef="1235" Label="noun"/>
					</Morph>
					<Morph>
						<MoForm DbRef="1236" Label="-s"/>
						<MSI DbRef="1237" Label="PL"/>
					</Morph>
				</Morphs>
			</WfiAnalysis>
			<WfiAnalysis>
				<Morphs>
					<Morph>
						<MoForm DbRef="1234" Label="bear"/>
						<MSI DbRef="1238" Label="verb"/>
					</Morph>
					<Morph>
						<MoForm DbRef="1500" Label="-s"/>
						<MSI DbRef="1501" Label="3.sg.agr"/>
					</Morph>
				</Morphs>
			</WfiAnalysis>
		</WordForm>
		<WordForm DbRef="1700" Form="eat">
			<WfiAnalysis>
				<Morphs>
					<Morph>
						<MoForm DbRef="6000" Label="eat"/>
						<MSI DbRef="1239" Label="v.t."/>
					</Morph>
				</Morphs>
			</WfiAnalysis>
		</WordForm>
	</WordSet>
</AnalyzingAgentResults>
