=== 2pages/FieldWorksMacOS/DistFiles/Languages/LanguageDefinition.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--If any change is made in this file, you also need to modify enum and g_rgeti in fw\src\language\LangDef.cpp
	and code in fw\src\WorldPad\WpXml.cpp. -->
<!ELEMENT Abbr24 (AUni)*>
<!ELEMENT AStr (Run)*>
<!ATTLIST AStr
	ws CDATA #REQUIRED
>
<!ELEMENT AUni (#PCDATA)>
<!ATTLIST AUni
	ws CDATA #REQUIRED
>
<!ELEMENT BaseLocale (#PCDATA)>
<!ELEMENT Boolean EMPTY>
<!ATTLIST Boolean
	val (false | true) #REQUIRED
>
<!ELEMENT CharDef EMPTY>
<!ATTLIST CharDef
	code CDATA #REQUIRED
	data CDATA #REQUIRED
>
<!ELEMENT CollationElements (#PCDATA)>
<!ELEMENT Collations24 (LgCollation)*>
<!ATTLIST Collations24
	size CDATA #IMPLIED
>
<!ELEMENT DefaultMonospace24 (Uni)?>
<!ELEMENT DefaultSansSerif24 (Uni)?>
<!ELEMENT DefaultBodyFont24 (Uni)?>
<!ELEMENT DefaultSerif24 (Uni)?>
<!ELEMENT Description24 (AStr)*>
<!ELEMENT EncodingConverter EMPTY>
<!ATTLIST EncodingConverter
	install CDATA #IMPLIED
	file CDATA #IMPLIED
>
<!ELEMENT Font EMPTY>
<!ATTLIST Font
	file CDATA #REQUIRED
>
<!ELEMENT Fonts (Font)*>
<!ELEMENT FontVariation24 (Uni)?>
<!ELEMENT SansFontVariation24 (Uni)?>
<!ELEMENT BodyFontFeatures24 (Uni)?>
<!ELEMENT ICULocale24 (Uni)?>
<!ELEMENT ValidChars24 (Uni)?>
<!ELEMENT SpellCheckDictionary24 (Uni)?>
<!ELEMENT IcuResourceName30 (Uni)?>
<!ELEMENT IcuResourceText30 (Uni)?>
<!ELEMENT ICURules30 (Uni)?>
<!ELEMENT Integer EMPTY>
<!ATTLIST Integer
	val CDATA #REQUIRED
	str CDATA #IMPLIED
>
<!ELEMENT Keyboard EMPTY>
<!ATTLIST Keyboard
	file CDATA #IMPLIED
>
<!ELEMENT KeyboardType24 (Uni)?>
<!ELEMENT KeymanKeyboard24 (Uni)?>
<!ELEMENT LanguageDefinition (LgWritingSystem | BaseLocale | NewLocale | EthnoCode | LocaleName | LocaleScript | LocaleCountry | LocaleVariant | LocaleWinLCID | CollationElements | LocaleResources | PuaDefinitions | Fonts | Keyboard | EncodingConverter)*>
<!ATTLIST LanguageDefinition
	xmlns:xsd CDATA #IMPLIED
	xmlns:xsi CDATA #IMPLIED
>
<!ELEMENT LegacyMapping24 (Uni)?>
<!ELEMENT LgCollation (IcuResourceName30 | IcuResourceText30 | ICURules30 | Name30 | WinCollation30 | WinLCID30)*>
<!ATTLIST LgCollation
	id ID #IMPLIED
	ord CDATA #IMPLIED
>
<!ELEMENT LgWritingSystem (Abbr24 | BodyFontFeatures24 | CapitalizationInfo24 | Collations24 | DefaultBodyFont24 | DefaultMonospace24 | DefaultSansSerif24 | DefaultSerif24 | Description24 | FontVariation24 | ICULocale24 | KeyboardType24 | KeymanKeyboard24 | LastModified24 | LegacyMapping24 | Locale24 | MatchedPairs24 | Name24 | PunctuationPatterns24 | QuotationMarks24 | RightToLeft24 | SansFontVariation24 | SpellCheckDictionary24 | ValidChars24)*>
<!ATTLIST LgWritingSystem
	id ID #IMPLIED
	language CDATA #IMPLIED
	type CDATA #IMPLIED
>

<!ELEMENT CapitalizationInfo24 (#PCDATA)>
<!ELEMENT EthnoCode (#PCDATA)>
<!ELEMENT LastModified24 (Time)?>
<!ELEMENT Locale24 (Integer)?>
<!ELEMENT LocaleCountry (#PCDATA)>
<!ELEMENT LocaleName (#PCDATA)>
<!ELEMENT LocaleResources (#PCDATA)>
<!ELEMENT LocaleScript (#PCDATA)>
<!ELEMENT LocaleVariant (#PCDATA)>
<!ELEMENT LocaleWinLCID (#PCDATA)>
<!ELEMENT MatchedPairs24 (Uni)?>
<!ELEMENT Name24 (AUni)*>
<!ELEMENT Name30 (AUni)*>
<!ELEMENT NewLocale (#PCDATA)>
<!ELEMENT PuaDefinitions (CharDef)*>
<!ELEMENT PunctuationPatterns24 (Uni)?>
<!ELEMENT QuotationMarks24 (Uni)?>
<!ELEMENT RightToLeft24 (Boolean)?>
<!ELEMENT Run (#PCDATA)>
<!ATTLIST Run
	type (chars | picture) #IMPLIED
	backcolor CDATA #IMPLIED
	bold (invert | off | on) #IMPLIED
	ws CDATA #REQUIRED
	wsBase CDATA #IMPLIED
	externalLink CDATA #IMPLIED
	fontFamily CDATA #IMPLIED
	fontsize CDATA #IMPLIED
	fontsizeUnit CDATA #IMPLIED
	forecolor CDATA #IMPLIED
	italic (invert | off | on) #IMPLIED
	link CDATA #IMPLIED
	namedStyle CDATA #IMPLIED
	offset CDATA #IMPLIED
	offsetUnit CDATA #IMPLIED
	superscript (sub | super) #IMPLIED
	tabList CDATA #IMPLIED
	tags IDREFS #IMPLIED
	undercolor CDATA #IMPLIED
	underline (dashed | dotted | double | none | single) #IMPLIED
>
<!ELEMENT Time EMPTY>
<!ATTLIST Time
	val CDATA #REQUIRED
>
<!ELEMENT Uni (#PCDATA)>
<!ELEMENT WinCollation30 (Uni)?>
<!ELEMENT WinLCID30 (Integer)?>

=== 2pages/FieldWorksMacOS/Src/LangInst/InstallLanguageTests/pua.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LanguageDefinition SYSTEM "LanguageDefinition.dtd">
<LanguageDefinition>
  <LgWritingSystem>
	<Locale24>
	  <Integer val="13321"/>
	</Locale24>
	<DefaultMonospace24>
	  <Uni>Courier New</Uni>
	</DefaultMonospace24>
	<DefaultSansSerif24>
	  <Uni>Arial</Uni>
	</DefaultSansSerif24>
	<DefaultSerif24>
	  <Uni>Times New Roman</Uni>
	</DefaultSerif24>
	<ICULocale24>
	  <Uni>tl</Uni>
	</ICULocale24>
	<Name24>
	  <AUni ws="en">Tagalog</AUni>
	</Name24>
	<Abbr24>
	  <AUni ws="en">TGL</AUni>
	</Abbr24>
	<Description24>
	  <AStr ws="en">
		<Run ws="en">The standard alphabetic representation of Tagalog (Philippines).</Run>
	  </AStr>
	</Description24>
	<Collations24>
	  <LgCollation>
		<WinLCID30>
		  <Integer val="1033"/>
		</WinLCID30>
		<WinCollation30>
		  <Uni>Latin1_General_CI_AI</Uni>
		</WinCollation30>
		<Name30>
		  <AUni ws="en">Default Collation</AUni>
		</Name30>
	  </LgCollation>
	</Collations24>
  </LgWritingSystem>
  <BaseLocale/>
  <NewLocale>tl</NewLocale>
  <LocaleName>Tagalog</LocaleName>
  <LocaleCountry/>
  <LocaleVariant/>
<!-- This LCID is for English in the Philippines. Microsoft has not defined one for Tagalog. -->
  <LocaleWinLCID>13321</LocaleWinLCID>
  <CollationElements>"&amp; B &lt; ċ &lt;&lt;&lt; Ċ" // ċ  Ċ
"    &lt; c&lt;&lt;&lt;C"
</CollationElements>
  <LocaleResources>
	zoneStrings {
		{
			"Europe/London",
			"Greenwich Mean Time",
			"GMT",
			"British Summer Time",
			"BST",
		}
	}
</LocaleResources>
  <PuaDefinitions><!-- These codes are intentionally out of order --><CharDef code="F136" data="PIGDASH;Mn;0;NSM;;;;;N;;;;;"/><CharDef code="F137" data="PIG Curlytail;Mn;0;NSM;;;;;N;;;;;"/><CharDef code="F139" data="PIG Jump;Ll;0;L;;;;;N;;;;;"/><CharDef code="F171" data="PIGCHARACTER UGLY;Ll;0;R;;;;;N;;;;;"/><!-- Tests all the fields:
2: Sm (Mathematical symbol)
3: 0 (is an ordinary spacing character)
4: R ( is a right-to-left character )
5: <compat> 0050 (is a decomposition of "P")
6,7,8: Number field are not applicable for letter
9: Y (mirrored in Bi-directional text)
10: OLD NAME OF JIBBERISH (the "unicode 1.0" name of this character)
11: NO COMMENT (ISO comment, technically it should be <none> but this is being used to test)
12,13,14: 0050;0070;0050 (this character has an upper-case equivalent 0050, a lower-case equivelent 0070, and a title-case equivelent: 0050)
--><CharDef code="F16F" data="JIBBERISH SMALL LETTER P WITH TWO STROKES;Sm;0;EN;&lt;compat&gt; 0050;;;;Y;OLD NAME OF JIBBERISH;NO COMMENT;0050;0070;0050"/>
<CharDef code="E001" data="PIG NUMERAL 1;Nd;0;NSM;;;;;N;;;;;"/><CharDef code="E002" data="PIG NUMERAL 2;Nd;0;L;;;;;N;;;;;"/><CharDef code="F0EE" data="PIG NUMERAL 6;Nd;0;L;;;;;N;;;;;"/><!-- Tests all the fields:
2: Nd (Number decimal digit)
3: 228 (canonical combining: above left)
4: EN ( Bidi Class value: is a European number character )
5: <small> 0034 (is a decomposition of "4")
6,7,8: 4;4;4; (Numeric equivalent is "4")
9: N (Not mirrored in Bi-directional text)
10: PIGGY 4 (the "unicode 1.0" name of this character)
11: <none> (ISO comment)
12,13,14: ;;; (no upper case equivelant)
--><!--<OldCharDef code="F00E" data="PIG NUMERAL 4;Nd;228;EN;&lt;small&gt; 0034;4;4;4;N;PIGGY 4;&lt;none&gt;;;;"/> --><CharDef code="F00E" data="PIG NUMERAL 4;Mn;228;NSM;&lt;small&gt; 0034;4;4;4;N;PIGGY 4;&lt;none&gt;;;;"/>
<CharDef code="F00D" data="PIG NUMERAL 3;Nd;228;EN;0033;3;3;3;N;PIGGY 3;&lt;none&gt;;;;"/><CharDef code="F0ED" data="PIG NUMERAL 5;Nd;0;L;;;;;N;;;;;"/><CharDef code="F12F" data="PIG NUMERAL 8;Nd;0;R;;;;;N;;;;;"/><CharDef code="F12E" data="PIG NUMERAL 7;Nd;0;L;;;;;N;;;;;"/></PuaDefinitions>
  <Fonts>
	<Font file="arial.ttf"/>
	<Font file="arialbd.ttf"/>
	<Font file="ariali.ttf"/>
	<Font file="arialbi.ttf"/>
	<Font file="times.ttf"/>
	<Font file="timesbd.ttf"/>
	<Font file="timesbi.ttf"/>
	<Font file="timesi.ttf"/>
  </Fonts>
  <Keyboard file="Tagalog.kmx"/>
  <EncodingConverter install="SIL_IPA93.tec.vbs" file="SIL-IPA93.tec"/>
</LanguageDefinition>
